[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "agpyutils"
version = "0.1.1"
description = "shared utils for agdev services"
requires-python = ">=3.9"
dependencies = [
  "httpx",
  "PyJWT",
  "fastapi"
]
